In [87]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [88]:
df=pd.read_csv("SPAM text message 20170820 - Data.csv")

In [89]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [304]:
df11=pd.DataFrame(np.random.randn(4,2), index=list('0123'),columns=[1,2])
df11

          1         2
0  0.060154  0.150481
1  0.410195 -0.616884
2  0.079509  1.065463
3 -1.584974 -0.529946

In [182]:
X = df.Category

In [183]:
y= df.Message

In [191]:
Message=pd.DataFrame(y,columns=['Message'])
Message.isnull().sum()

Message    0
dtype: int64

In [185]:
scaler =  LabelEncoder()

In [186]:
label_encoded_data=scaler.fit_transform(X)

#

In [197]:
D=label_encoded_data.reshape(-1,1)
Category=pd.DataFrame(D,columns =['Category'])
Category

      Category
0            0
1            0
2            1
3            0
4            0
...        ...
5567         1
5568         0
5569         0
5570         0
5571         0

[5572 rows x 1 columns]

In [201]:
email=pd.concat([Category,Message],axis=1)

In [202]:
email.isnull().sum()

Category    0
Message     0
dtype: int64

In [205]:

email.sort_index(inplace=True)

In [206]:
from sklearn.feature_extraction.text import CountVectorizer

In [290]:
vectorizer=CountVectorizer(stop_words='english')

In [291]:
features=vectorizer.fit_transform(email.Message)

In [292]:
features.shape

(5572, 8440)

In [293]:
vectorizer.vocabulary_

{'jurong': 4244,
 'point': 5775,
 'crazy': 2278,
 'available': 1281,
 'bugis': 1715,
 'great': 3551,
 'world': 8281,
 'la': 4370,
 'buffet': 1713,
 'cine': 2003,
 'got': 3511,
 'amore': 1061,
 'wat': 8079,
 'ok': 5373,
 'lar': 4406,
 'joking': 4212,
 'wif': 8187,
 'oni': 5399,
 'free': 3276,
 'entry': 2885,
 'wkly': 8239,
 'comp': 2119,
 'win': 8199,
 'fa': 3014,
 'cup': 2337,
 'final': 3131,
 'tkts': 7565,
 '21st': 410,
 '2005': 401,
 'text': 7433,
 '87121': 791,
 'receive': 6154,
 'question': 6048,
 'std': 7073,
 'txt': 7750,
 'rate': 6100,
 'apply': 1138,
 '08452810075over18': 77,
 'dun': 2747,
 'say': 6492,
 'early': 2766,
 'hor': 3836,
 'nah': 5120,
 'don': 2659,
 'think': 7488,
 'goes': 3475,
 'usf': 7888,
 'lives': 4558,
 'freemsg': 3283,
 'hey': 3753,
 'darling': 2394,
 'week': 8125,
 'word': 8272,
 'like': 4508,
 'fun': 3338,
 'tb': 7368,
 'xxx': 8346,
 'chgs': 1957,
 'send': 6580,
 '50': 613,
 'rcv': 6112,
 'brother': 1685,
 'speak': 6955,
 'treat': 7683,
 'aids': 994,
 'patent': 5578,
 'request': 6263,
 'melle': 4858,
 'oru': 5457,
 'minnaminunginte': 4923,
 'nurungu': 5311,
 'vettam': 7945,
 'set': 6606,
 'callertune': 1783,
 'callers': 1782,
 'press': 5898,
 'copy': 2220,
 'friends': 3300,
 'winner': 8210,
 'valued': 7915,
 'network': 5197,
 'customer': 2350,
 'selected': 6566,
 'receivea': 6155,
 '900': 823,
 'prize': 5930,
 'reward': 6318,
 'claim': 2009,
 '09061701461': 222,
 'code': 2074,
 'kl341': 4333,
 'valid': 7911,
 '12': 321,
 'hours': 3856,
 'mobile': 4977,
 '11': 310,
 'months': 5017,
 'entitled': 2882,
 'update': 7851,
 'latest': 4419,
 'colour': 2095,
 'mobiles': 4978,
 'camera': 1794,
 '08002986030': 61,
 'gonna': 3491,
 'home': 3809,
 'soon': 6910,
 'want': 8059,
 'talk': 7335,
 'stuff': 7162,
 'anymore': 1109,
 'tonight': 7614,
 've': 7930,
 'cried': 2295,
 'today': 7584,
 'chances': 1898,
 'cash': 1844,
 '100': 296,
 '20': 396,
 '000': 1,
 'pounds': 5838,
 'csh11': 2313,
 '87575': 796,
 'cost': 2232,
 '150p': 350,
 'day': 2410,
 '6days': 687,
 '16': 362,
 'tsandcs': 7717,
 'reply': 6256,
 'hl': 3781,
 'info': 4025,
 'urgent': 7868,
 'won': 8256,
 'membership': 4864,
 'jackpot': 4140,
 '81010': 744,
 'www': 8328,
 'dbuk': 2415,
 'net': 5191,
 'lccltd': 4437,
 'pobox': 5754,
 '4403ldnw1a7rw18': 563,
 'searching': 6539,
 'right': 6330,
 'words': 8273,
 'thank': 7449,
 'breather': 1654,
 'promise': 5963,
 'wont': 8263,
 'help': 3733,
 'granted': 3540,
 'fulfil': 3335,
 'wonderful': 8260,
 'blessing': 1532,
 'times': 7543,
 'date': 2402,
 'sunday': 7229,
 'xxxmobilemovieclub': 8347,
 'use': 7882,
 'credit': 2285,
 'click': 2032,
 'wap': 8064,
 'link': 4530,
 'message': 4882,
 'http': 3876,
 'com': 2098,
 'qjkgighjjgcbl': 6040,
 'oh': 5368,
 'watching': 8084,
 'eh': 2812,
 'remember': 6223,
 'spell': 6970,
 'yes': 8383,
 'did': 2542,
 'naughty': 5152,
 'make': 4742,
 'wet': 8160,
 'fine': 3138,
 'way': 8096,
 'feel': 3085,
 'gota': 3512,
 'england': 2864,
 'macedonia': 4705,
 'dont': 2662,
 'miss': 4939,
 'goals': 3471,
 'team': 7380,
 'news': 5210,
 'ur': 7864,
 'national': 5146,
 '87077': 790,
 'try': 7713,
 'wales': 8039,
 'scotland': 6518,
 '4txt': 605,
 'ú1': 8438,
 'poboxox36504w45wq': 5766,
 'seriously': 6599,
 'going': 3480,
 'ha': 3613,
 'pay': 5590,
 'da': 2367,
 'stock': 7098,
 'comin': 2109,
 'aft': 968,
 'finish': 3141,
 'lunch': 4671,
 'str': 7123,
 'lor': 4613,
 'ard': 1164,
 'smth': 6858,
 'ffffffffff': 3104,
 'alright': 1040,
 'meet': 4847,
 'sooner': 6911,
 'just': 4246,
 'forced': 3230,
 'eat': 2778,
 'slice': 6810,
 'really': 6136,
 'hungry': 3895,
 'tho': 7503,
 'sucks': 7198,
 'mark': 4778,
 'getting': 3429,
 'worried': 8284,
 'knows': 4344,
 'sick': 6731,
 'turn': 7736,
 'pizza': 5710,
 'lol': 4590,
 'convincing': 2208,
 'catch': 1854,
 'bus': 1735,
 'frying': 3323,
 'egg': 2809,
 'tea': 7374,
 'eating': 2781,
 'mom': 4998,
 'left': 4460,
 'dinner': 2573,
 'love': 4635,
 'amp': 1062,
 'packing': 5510,
 'car': 1816,
 'll': 4562,
 'let': 4480,
 'know': 4341,
 'room': 6371,
 'ahhh': 989,
 'work': 8274,
 'vaguely': 7907,
 'does': 2635,
 'wait': 8033,
 'clear': 2026,
 'sure': 7255,
 'sarcastic': 6470,
 'doesn': 2637,
 'live': 4554,
 'yeah': 8371,
 'apologetic': 1125,
 'fallen': 3039,
 'actin': 909,
 'spoilt': 6997,
 'child': 1965,
 'caught': 1858,
 'till': 7540,
 'doing': 2649,
 'badly': 1331,
 'cheers': 1941,
 'tell': 7398,
 'fear': 3077,
 'fainting': 3031,
 'housework': 3860,
 'quick': 6051,
 'cuppa': 2339,
 'thanks': 7450,
 'subscription': 7187,
 'ringtone': 6339,
 'uk': 7780,
 'charged': 1910,
 'month': 5014,
 'confirm': 2163,
 'replying': 6257,
 'yup': 8422,
 'look': 4601,
 'timings': 7547,
 'msg': 5053,
 'xuhui': 8342,
 'learn': 4451,
 '2nd': 464,
 'lesson': 4478,
 '8am': 816,
 'oops': 5412,
 'roommate': 6373,
 'letter': 4482,
 'decide': 2432,
 'hello': 3730,
 'saturday': 6483,
 'texting': 7441,
 'decided': 2433,
 'tomo': 7603,
 'trying': 7715,
 'invite': 4081,
 'pls': 5742,
 'ahead': 988,
 'watts': 8092,
 'wanted': 8061,
 'weekend': 8127,
 'abiola': 863,
 'forget': 3236,
 'need': 5172,
 'crave': 2275,
 'sweet': 7286,
 'arabian': 1161,
 'steed': 7080,
 'mmmmmm': 4967,
 'yummy': 8417,
 '07732584351': 30,
 'rodger': 6361,
 'burns': 1732,
 'tried': 7692,
 'sms': 6853,
 'nokia': 5254,
 'camcorder': 1792,
 '08000930705': 57,
 'delivery': 2472,
 'tomorrow': 7605,
 'seeing': 6557,
 'hope': 3827,
 'man': 4752,
 'endowed': 2854,
 'lt': 4659,
 'gt': 3580,
 'inches': 3995,
 'calls': 1788,
 'messages': 4884,
 'missed': 4941,
 'didn': 2544,
 'hep': 3744,
 'immunisation': 3976,
 'nigeria': 5223,
 'fair': 3032,
 'hopefully': 3830,
 'tyler': 7763,
 'maybe': 4823,
 'ask': 1213,
 'bit': 1509,
 'stubborn': 7151,
 'hospital': 3843,
 'kept': 4290,
 'telling': 7399,
 'weak': 8101,
 'sucker': 7196,
 'hospitals': 3844,
 'suckers': 7197,
 'thinked': 7489,
 'time': 7542,
 'saw': 6491,
 'class': 2018,
 'gram': 3532,
 'usually': 7894,
 'runs': 6414,
 'half': 3628,
 'eighth': 2814,
 'smarter': 6833,
 'gets': 3425,
 'second': 6543,
 'fyi': 3353,
 'ride': 6329,
 'morning': 5024,
 'crashing': 2274,
 'place': 5712,
 'wow': 8299,
 'realized': 6134,
 'embarassed': 2835,
 'accomodations': 892,
 'thought': 7506,
 'liked': 4509,
 'best': 1466,
 'happy': 3663,
 'cave': 1862,
 'sorry': 6920,
 'offered': 5355,
 'embarassing': 2836,
 'ac': 878,
 'sptv': 7019,
 'new': 5205,
 'jersey': 4182,
 'devils': 2522,
 'detroit': 2516,
 'red': 6177,
 'wings': 8208,
 'play': 5726,
 'ice': 3929,
 'hockey': 3794,
 'correct': 2225,
 'incorrect': 4006,
 'end': 2849,
 'mallika': 4751,
 'sherawat': 6656,
 'yesterday': 8385,
 'url': 7875,
 'congrats': 2169,
 'year': 8372,
 'special': 6957,
 'cinema': 2004,
 'pass': 5567,
 '09061209465': 217,
 'suprman': 7253,
 'matrix3': 4811,
 'starwars3': 7061,
 'bx420': 1756,
 'ip4': 4090,
 '5we': 648,
 '150pm': 352,
 'later': 4418,
 'meeting': 4849,
 'reached': 6118,
 'gauti': 3387,
 'sehwag': 6563,
 'odi': 5348,
 'series': 6598,
 'pick': 5682,
 'burger': 1727,
 'pain': 5517,
 'killing': 4315,
 'good': 3493,
 'joke': 4208,
 'girls': 3447,
 'situation': 6777,
 'seekers': 6558,
 'checking': 1935,
 'iq': 4096,
 'roommates': 6374,
 'took': 7619,
 'forever': 3233,
 'come': 2104,
 'double': 2677,
 'check': 1931,
 'hair': 3623,
 'dresser': 2706,
 'said': 6440,
 'wun': 8327,
 'cut': 2354,
 'short': 6692,
 'nice': 5217,
 'pleased': 5735,
 'advise': 951,
 'following': 3211,
 'recent': 6158,
 'review': 6316,
 'mob': 4975,
 'awarded': 1298,
 '1500': 349,
 'bonus': 1573,
 '09066364589': 265,
 'song': 6905,
 'dedicated': 2443,
 'dedicate': 2442,
 'valuable': 7913,
 'frnds': 3309,
 'rply': 6390,
 'complimentary': 2138,
 'trip': 7693,
 'eurodisinc': 2927,
 'trav': 7675,
 'aco': 906,
 'entry41': 2886,
 '1000': 297,
 'dis': 2585,
 '18': 367,
 'morefrmmob': 5021,
 'shracomorsglsuplt': 6715,
 '10': 295,
 'ls1': 4655,
 '3aj': 522,
 'hear': 3708,
 'divorce': 2614,
 'barbie': 1362,
 'comes': 2106,
 'ken': 4288,
 'plane': 5718,
 'wah': 8026,
 'lucky': 4665,
 'save': 6487,
 'money': 5005,
 'hee': 3721,
 'finished': 3143,
 'hi': 3757,
 'babe': 1318,
 'im': 3964,
 'wanna': 8057,
 'xx': 8343,
 'performed': 5627,
 'waiting': 8036,
 'machan': 4707,
 'thats': 7460,
 'cool': 2213,
 'gentleman': 3413,
 'dignity': 2563,
 'respect': 6283,
 'peoples': 5620,
 'shy': 6726,
 'pa': 5506,
 'operate': 5419,
 'looking': 4605,
 'job': 4197,
 'ta': 7313,
 'earn': 2767,
 'ah': 986,
 'stop': 7108,
 'urgnt': 7871,
 'real': 6127,
 'yo': 8394,
 'tickets': 7530,
 'jacket': 4139,
 'used': 7883,
 'multis': 5079,
 'started': 7056,
 'requests': 6264,
 'came': 1793,
 'bed': 1427,
 'coins': 2080,
 'factory': 3021,
 'gotta': 3517,
 'nitros': 5241,
 'ela': 2818,
 'kano': 4270,
 'il': 3958,
 'download': 2684,
 'wen': 8144,
 'stand': 7044,
 'close': 2039,
 'night': 5225,
 'spent': 6975,
 'late': 4415,
 'afternoon': 970,
 'casualty': 1852,
 'means': 4836,
 'haven': 3688,
 'stuff42moro': 7163,
 'includes': 3999,
 'sheets': 6651,
 'smile': 6841,
 'pleasure': 5737,
 'trouble': 7700,
 'pours': 5840,
 'rain': 6074,
 'sum1': 7220,
 'hurts': 3905,
 'becoz': 1425,
 'loves': 4643,
 'smiling': 6845,
 'service': 6602,
 'representative': 6261,
 '0800': 53,
 '169': 365,
 '6031': 654,
 '10am': 305,
 '9pm': 843,
 'guaranteed': 3584,
 '5000': 615,
 'havent': 3689,
 'planning': 5722,
 'buy': 1746,
 'lido': 4493,
 '530': 634,
 'collected': 2089,
 'simply': 6752,
 'password': 5574,
 'mix': 4957,
 '85069': 777,
 'verify': 7941,
 'usher': 7889,
 'britney': 1675,
 'fml': 3202,
 'po': 5752,
 'box': 1605,
 '5249': 631,
 'mk17': 4960,
 '92h': 828,
 '450ppw': 572,
 'telugu': 7404,
 'movie': 5042,
 'abt': 873,
 'loads': 4569,
 'loans': 4571,
 'wk': 8235,
 'hols': 3807,
 'run': 6412,
 'forgot': 3241,
 'hairdressers': 3625,
 'appointment': 1141,
 'shower': 6708,
 'cause': 1859,
 'prob': 5935,
 'coffee': 2075,
 'animation': 1082,
 'okay': 5374,
 'price': 5911,
 'long': 4597,
 'legal': 4463,
 'ave': 1285,
 'ams': 1066,
 'gone': 3489,
 '4the': 603,
 'driving': 2715,
 'test': 7427,
 'mean': 4832,
 'guess': 3590,
 'gave': 3388,
 'boston': 1594,
 'men': 4868,
 'changed': 1900,
 'search': 6538,
 'location': 4574,
 'nyc': 5322,
 'cuz': 2361,
 'signin': 6740,
 'page': 5513,
 'says': 6496,
 'umma': 7787,
 'life': 4496,
 'vava': 7927,
 'lot': 4621,
 'dear': 2422,
 'wishes': 8222,
 'birthday': 1507,
 'making': 4746,
 'truly': 7708,
 'memorable': 4865,
 'aight': 996,
 'hit': 3774,
 'ip': 4089,
 'address': 927,
 'considering': 2181,
 'computer': 2144,
 'isn': 4113,
 'minecraft': 4917,
 'server': 6601,
 'grumpy': 3577,
 'old': 5386,
 'people': 5619,
 'better': 1472,
 'lying': 4685,
 'jokes': 4210,
 'worry': 8286,
 'busy': 1741,
 'plural': 5746,
 'noun': 5290,
 'research': 6269,
 'cos': 2230,
 'things': 7487,
 'scared': 6502,
 'mah': 4729,
 'loud': 4630,
 'gent': 3411,
 'contact': 2186,
 'weekends': 8128,
 'draw': 2698,
 'shows': 6714,
 '09064012160': 241,
 'k52': 4253,
 '12hrs': 332,
 '150ppm': 354,
 'wa': 8021,
 'openin': 5416,
 'sentence': 6591,
 'formal': 3245,
 'juz': 4252,
 'tt': 7723,
 'eatin': 2780,
 'puttin': 6030,
 'weight': 8133,
 'haha': 3619,
 'anythin': 1113,
 'happened': 3655,
 'entered': 2875,
 'cabin': 1762,
 'boss': 1593,
 'felt': 3095,
 'askd': 1214,
 'invited': 4082,
 'apartment': 1119,
 'went': 8147,
 'specially': 6961,
 'holiday': 3804,
 'flights': 3178,
 'operator': 5420,
 '0871277810910p': 129,
 'min': 4911,
 'goodo': 3502,
 'friday': 3295,
 'potato': 5832,
 'ratio': 6102,
 'tortilla': 7635,
 'needed': 5174,
 'hmm': 3786,
 'uncle': 7795,
 'informed': 4028,
 'paying': 5596,
 'school': 6508,
 'directly': 2579,
 'food': 3219,
 'private': 5927,
 '2004': 400,
 'account': 895,
 'statement': 7064,
 '07742676969': 32,
 '786': 716,
 'unredeemed': 7838,
 'points': 5776,
 '08719180248': 174,
 'identifier': 3941,
 '45239': 574,
 'expires': 2993,
 '2000': 398,
 'caller': 1781,
 '03': 15,
 'landline': 4393,
 '09064019788': 247,
 'box42wr29c': 1617,
 'apples': 1136,
 'pairs': 5521,
 'malarky': 4748,
 'todays': 7585,
 'voda': 7990,
 'numbers': 5308,
 'ending': 2851,
 '7548': 708,
 '350': 510,
 'award': 1297,
 'match': 4799,
 '08712300220': 111,
 'quoting': 6062,
 '4041': 547,
 'standard': 7045,
 'rates': 6101,
 'app': 1129,
 'sao': 6464,
 'mu': 5069,
 'predict': 5872,
 'buying': 1749,
 'yetunde': 8387,
 'hasn': 3675,
 'sent': 6590,
 'bother': 1596,
 'sending': 6582,
 'involve': 4086,
 'shouldn': 6702,
 'imposed': 3983,
 'apologise': 1126,
 'girl': 3444,
 'del': 2462,
 'bak': 1339,
 'sum': 7219,
 'lucyxx': 4668,
 'tmorrow': 7571,
 'accomodate': 891,
 'answer': 1097,
 'sunshine': 7236,
 'quiz': 6058,
 'sony': 6907,
 'dvd': 2756,
 'player': 5728,
 'country': 2247,
 'algarve': 1024,
 'ansr': 1096,
 '82277': 751,
 'sp': 6942,
 'tyrone': 7767,
 'laid': 4385,
 'dogging': 2643,
 'locations': 4575,
 'direct': 2578,
 'join': 4205,
 'largest': 4410,
 'bt': 1701,
 'txting': 7756,
 'gravel': 3545,
 '69888': 682,
 'nt': 5298,
 'ec2a': 2783,
 '31p': 502,
 'haf': 3618,
 'msn': 5060,
 'yijue': 8391,
 'hotmail': 3851,
 'rooms': 6375,
 'befor': 1438,
 'activities': 915,
 'msgs': 5059,
 'chat': 1921,
 'svc': 7271,
 'hardcore': 3665,
 'services': 6603,
 '69988': 686,
 'age': 975,
 'yr': 8412,
 'lazy': 4436,
 'type': 7764,
 'lect': 4457,
 'pouch': 5835,
 'sir': 6766,
 'mail': 4734,
 'swt': 7300,
 'nver': 5316,
 'tired': 7551,
 'little': 4553,
 'lovable': 4634,
 'persons': 5644,
 'coz': 2260,
 'somtimes': 6902,
 'occupy': 5341,
 'biggest': 1490,
 'hearts': 3714,
 'gud': 3586,
 'ni8': 5215,
 'open': 5413,
 'ya': 8356,
 'dot': 2676,
 'whats': 8164,
 'staff': 7036,
 'taking': 7332,
 'replied': 6254,
 'randy': 6094,
 'sexy': 6618,
 'female': 3096,
 'local': 4573,
 'luv': 4676,
 'netcollex': 5192,
 '08700621170150p': 81,
 'ummma': 7789,
 'begin': 1442,
 'qatar': 6035,
 'pray': 5867,
 'hard': 3664,
 'deleted': 2466,
 'sindu': 6756,
 'birla': 1503,
 'soft': 6879,
 'wine': 8206,
 'flowing': 3193,
 'nevering': 5202,
 'thk': 7497,
 'plaza': 5733,
 'typical': 7766,
 'dirt': 2582,
 'floor': 3187,
 'windows': 8203,
 'shirt': 6671,
 'mouth': 5039,
 'dream': 2701,
 'chores': 1992,
 'joy': 4223,
 'lots': 4623,
 'tv': 7741,
 'exist': 2978,
 'hail': 3622,
 'mist': 4949,
 'aaooooright': 853,
 'leaving': 4456,
 'house': 3857,
 'interview': 4069,
 'boy': 1622,
 'missing': 4943,
 'annoncement': 1088,
 'years': 8373,
 '07046744435': 24,
 'arrange': 1190,
 '0871277810810': 128,
 'safe': 6435,
 'envy': 2891,
 'parents': 5550,
 'hand': 3637,
 'excited': 2966,
 'spend': 6973,
 'bootydelious': 1586,
 '32': 503,
 'inviting': 4083,
 'friend': 3299,
 '434': 560,
 'frnd': 3308,
 '62468': 662,
 'bangbabes': 1353,
 'order': 5441,
 'content': 2190,
 'goto': 3516,
 'bangb': 1352,
 'internet': 4068,
 'menu': 4875,
 'cultures': 2333,
 'module': 4991,
 '09061701939': 224,
 's89': 6425,
 'avoid': 1291,
 'missunderstding': 4947,
 'wit': 8227,
 'beloved': 1457,
 'escape': 2912,
 'fancy': 3050,
 'bridge': 1660,
 'needs': 5177,
 'lager': 4384,
 'completely': 2134,
 'form': 3244,
 'clark': 2015,
 'utter': 7896,
 'waste': 8076,
 'axis': 1306,
 'bank': 1355,
 'hmmm': 3787,
 'hop': 3826,
 'muz': 5103,
 'discuss': 2598,
 'liao': 4487,
 'coming': 2110,
 'bloody': 1546,
 'hell': 3728,
 'believe': 1448,
 'surname': 7261,
 'mr': 5048,
 'ill': 3960,
 'clue': 2055,
 'spanish': 6949,
 'begins': 1443,
 'bath': 1386,
 'carlos': 1833,
 'mall': 4750,
 'turns': 7739,
 'staying': 7071,
 'til': 7539,
 'smoke': 6847,
 'worth': 8290,
 'doesnt': 2638,
 'log': 4581,
 'spoke': 6998,
 'maneesha': 4762,
 'satisfied': 6479,
 'experience': 2988,
 'toll': 7598,
 'lifted': 4502,
 'hopes': 3832,
 'offer': 5354,
 'especially': 2916,
 'approaches': 1145,
 'studying': 7160,
 'anyways': 1116,
 'gr8': 3525,
 'trust': 7710,
 'guys': 3606,
 'bye': 1759,
 'handsome': 3643,
 'finding': 3136,
 'working': 8278,
 'mummy': 5083,
 'boytoy': 1627,
 'awesome': 1300,
 'minute': 4928,
 'freephone': 3284,
 '0808': 65,
 '145': 342,
 '4742': 578,
 '9am': 841,
 '11pm': 320,
 'xmas': 8339,
 'radio': 6067,
 'jus': 4245,
 'bathe': 1387,
 'sis': 6768,
 'using': 7890,
 'finishes': 3144,
 'unique': 7823,
 '30th': 498,
 'august': 1267,
 'areyouunique': 1170,
 'joined': 4206,
 'league': 4449,
 'touch': 7644,
 'deal': 2418,
 'personal': 5641,
 'finally': 3133,
 'completed': 2133,
 'course': 2253,
 'suggest': 7211,
 'stays': 7072,
 'able': 865,
 'ors': 5455,
 'stool': 7107,
 'settled': 6610,
 'wishin': 8223,
 'mrng': 5050,
 'hav': 3683,
 'story': 7122,
 'hamster': 3636,
 'dead': 2417,
 'tmr': 7572,
 '1pm': 384,
 ...}

In [213]:
from sklearn.model_selection import train_test_split

In [220]:
train_x, test_x,train_y,test_y=train_test_split(features,email.Category,test_size=0.3,random_state=88)

In [221]:
train_x.shape

(3900, 8440)

In [222]:
train_y.shape

(3900,)

In [224]:
test_x.shape

(1672, 8440)

In [225]:
test_y.shape

(1672,)

In [241]:
test_x

<1672x8440 sparse matrix of type '<class 'numpy.int64'>'
	with 13020 stored elements in Compressed Sparse Row format>

In [226]:
from sklearn.naive_bayes import MultinomialNB

In [227]:
classifier=MultinomialNB()

In [228]:
classifier.fit(train_x,train_y)

MultinomialNB()

In [235]:
nrr_correct=(test_y==classifier.predict(test_x)).sum()

In [240]:
test_y

2928    0
1315    0
679     0
5547    1
4460    1
       ..
919     0
1382    0
1831    0
3642    1
5034    0
Name: Category, Length: 1672, dtype: int32

In [237]:
classifier.predict(test_x)

array([0, 0, 0, ..., 0, 1, 0])

In [238]:
nrr_correct

1634

In [244]:
nrr_nocorrect=test_y.size-nrr_correct

In [245]:
nrr_nocorrect

38

In [248]:
fraction_correct=nrr_correct/(nrr_correct+nrr_nocorrect)

In [268]:
print('The tested accuracy of the model is',format(fraction_correct,".2%"))

The tested accuracy of the model is 97.73%

In [259]:
fraction_nocorrect=nrr_nocorrect/(nrr_correct+nrr_nocorrect)

In [267]:
print(format(fraction_nocorrect,".2%"))

2.27%

In [273]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

In [272]:
recall_score(test_y,classifier.predict(test_x))

0.9301310043668122

In [274]:
precision_score(test_y, classifier.predict(test_x))

0.9063829787234042

In [275]:
f1_score(test_y, classifier.predict(test_x))

0.918103448275862

In [283]:
sample = ['Hey Bro ,How are you?',
         'can you give me your phone? please',
          'Not signed up yet? No worries. Today is the best day to join the Lucky Star Tournament! You can claim a solid share of the $280,000 Prize pot and snatch up some amazing cash prizes, XP, & risk-free trades. And of course, a lot of priceless trading experience.',
           'At zomato, we have delivered 15 crore+ orders since the first lockdown in March. And there have been zero reported cases of COVID-19 transmission through food.Dr. Mike Ryan of World Health Organisation (WHO) has also said, “People should not fear food, food packaging, processing, or delivery of food. People should feel comfortable and safe."']

In [284]:
check=vectorizer.transform(sample)

In [285]:
classifier.predict(check)

array([0, 0, 1, 0])